version: "3"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENV=production
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
       - ./frontend/volumes/etc/letsencrypt:/etc/letsencrypt

  backend:
    build:
      context: ./backend
    ports:
      - "8081:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - APP_RL_STORAGE_URI=memcached://memcached:11211
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend/volumes/database:/app/volumes/database:z
    restart: unless-stopped

  memcached:
    image: memcached:1-alpine
    restart: unless-stopped
    command:
      - --memory-limit=64
    ports:
      - "11211:11211"
