services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    environment:
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8081:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./backend/volumes/database:/app/volumes/database:z
