services:
  frontend:
    environment:
      - NGINX_SERVER_NAME=localhost
    volumes:
      - ./frontend/output:/usr/share/nginx/html:z
  backend:
    environment:
      - SECRET_KEY=dev-secret-change-in-production
