version: "3"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENV=production
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}
    depends_on:
      - backend
    tty: true
    stdin_open: true
    volumes:
       - ./frontend/volumes/etc/letsencrypt:/etc/letsencrypt

  backend:
    build:
      context: ./backend
    ports:
      - "8081:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./backend/volumes/database:/app/volumes/database:z
